# Generated by Django 4.1.7 on 2023-03-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=64)),
                ('course', models.CharField(max_length=64)),
                ('file_url', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
