# Generated by Django 4.1.7 on 2023-03-21 05:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('pending', 'PENDING'), ('started', 'STARTED'), ('retry', 'RETRY'), ('failure', 'FAILURE'), ('success', 'SUCCESS')], default='pending', max_length=10)),
                ('task_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='participantdetails',
            name='participant_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
