# Generated by Django 4.1.7 on 2023-03-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_certificatedetails_delete_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatedetails',
            name='file_url',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
