# Generated by Django 4.1.7 on 2023-03-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_alter_certificatedetails_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatedetails',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
