# Generated by Django 4.1.7 on 2023-03-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_alter_tasklog_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact_form.participantdetails'),
            preserve_default=False,
        ),
    ]
